### ISSUE TITLE
Undefined property $key

### ISSUE THREAD

**Issue by rappasoft** [Retsly/php-sdk#5]
I used the example from the read me and I can't seem to figure out why i'm getting the following exception.

```
ErrorException in Request.php line 170:
Undefined property: Retsly\ListingRequest::$key
```

For the following code:

```
return $this->retsly
            ->listings()
            ->getAll();
```

All the supporting code is in place, $this->retsly is a Client object.

**Comment by slajax** [comment]
@rappasoft - Can you give us your php version and also run the tests?

**Comment by lvivier** [comment]
@rappasoft, the issue is due to some differences in how php 5.6 generates notices compared to older PHPs. I was able to reproduce your situation on my workstation with 5.6.17 and I've just published a new release of the SDK (0.3.0). It should be on Packagist shortly, let me know if you don't see it.

**Comment by rappasoft** [comment]
Awesome thanks!

**Comment by lvivier** [comment]
@rappasoft should be on Packagist now :ribbon:

**Comment by rappasoft** [comment]
Confirming it works! :thumbsup:
